# Generated by Django 5.0.7 on 2024-08-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('just_text', models.CharField(max_length=200, verbose_name='Just a field')),
            ],
        ),
    ]
