# Generated by Django 5.0.7 on 2024-08-06 10:03

from django.db import migrations

import mainapp

def add_sample_data(apps, schema_editor):
    SimpleModel = apps.get_model('mainapp', 'SimpleModel')
    SimpleModel.objects.create(just_text="text_1")
    SimpleModel.objects.create(just_text="text_2")


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_data),
    ]
